package mysql

type DataType uint

const (
	DATATYPE_BIT DataType = iota
	DATATYPE_TINYINT
	DATATYPE_SMALLINT
	DATATYPE_MEDIUMINT
	DATATYPE_INT
	DATATYPE_BIGINT
	DATATYPE_REAL
	DATATYPE_DOUBLE
	DATATYPE_FLOAT
	DATATYPE_DECIMAL
	DATATYPE_NUMERIC
	DATATYPE_DATE
	DATATYPE_TIME
	DATATYPE_TIMESTAMP
	DATATYPE_DATETIME
	DATATYPE_YEAR
	DATATYPE_CHAR
	DATATYPE_VARCHAR
	DATATYPE_BINARY
	DATATYPE_VARBINARY
	DATATYPE_TINYBLOB
	DATATYPE_BLOB
	DATATYPE_MEDIUMBLOB
	DATATYPE_LONGBLOB
	DATATYPE_TINYTEXT
	DATATYPE_TEXT
	DATATYPE_MEDIUMTEXT
	DATATYPE_LONGTEXT
)

func (t DataType) String() string {
	switch t {
	case DATATYPE_BIT:
		return "BIT"
	case DATATYPE_TINYINT:
		return "TINYINT"
	case DATATYPE_SMALLINT:
		return "SMALLINT"
	case DATATYPE_MEDIUMINT:
		return "MEDIUMINT"
	case DATATYPE_INT:
		return "INT"
	case DATATYPE_BIGINT:
		return "BIGINT"
	case DATATYPE_REAL:
		return "REAL"
	case DATATYPE_DOUBLE:
		return "DOUBLE"
	case DATATYPE_FLOAT:
		return "FLOAT"
	case DATATYPE_DECIMAL:
		return "DECIMAL"
	case DATATYPE_NUMERIC:
		return "NUMERIC"
	case DATATYPE_DATE:
		return "DATE"
	case DATATYPE_TIME:
		return "TIME"
	case DATATYPE_TIMESTAMP:
		return "TIMESTAMP"
	case DATATYPE_DATETIME:
		return "DATETIME"
	case DATATYPE_YEAR:
		return "YEAR"
	case DATATYPE_CHAR:
		return "CHAR"
	case DATATYPE_VARCHAR:
		return "VARCHAR"
	case DATATYPE_BINARY:
		return "BINARY"
	case DATATYPE_VARBINARY:
		return "VARBINARY"
	case DATATYPE_BLOB:
		return "BLOB"
	case DATATYPE_MEDIUMBLOB:
		return "MEDIUMBLOB"
	case DATATYPE_LONGBLOB:
		return "LONGBLOB"
	case DATATYPE_TINYTEXT:
		return "TINYTEXT"
	case DATATYPE_TEXT:
		return "TEXT"
	case DATATYPE_MEDIUMTEXT:
		return "MEDIUMTEXT"
	case DATATYPE_LONGTEXT:
		return "LONGTEXT"
	default:
		return ""
	}
}
